### ISSUE TITLE
Version 5 compatibility?

### ISSUE THREAD

**Issue by tomasvts** [airbrake/glog#11]
Are there any plans to make glog compatible with airbrake v5?

<img width="856" alt="image" src="https://user-images.githubusercontent.com/4351937/178587585-efc001a4-6a80-4228-840a-fac85ee4e692.png">

**Comment by chimanjain** [comment]
Thanks @tomasvts for bringing this issue to light, it was in our backlog, we will fix this issue and make it compatible with `gobrake v5`.
