### ISSUE TITLE
Introduce the ability to log stacktrace in glog while sending notice, for debug purposes.

### ISSUE THREAD

**Issue by ruseinov** [airbrake/glog#8]
This is something I've been missing out on while debugging a local statsman issue.

**Comment by ruseinov** [comment]
@zefer @vmihailenco see if that makes sense.

**Comment by vmihailenco** [comment]
Did you see https://github.com/golang/glog/blob/master/glog.go#L55-L61?

**Comment by ruseinov** [comment]
@vmihailenco That's good stuff which I didn't notice indeed, however if you're debugging several issues it's going to be impossible to do so without an app restart, if I'm not mistaken.

Being able to enable stacktrace for each error would be awesome, I can implement it if we agree that it might be useful, which for me it is already.

**Comment by vmihailenco** [comment]
That should be golang/glog feature, but they don't accept PRs. And I don't want to change/improve glog behaviour in this fork.

**Comment by ruseinov** [comment]
Gotcha
